[tool.poetry]
name = "local-spark"
version = "0.1.0"
description = ""
authors = ["Q"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyspark = "^3.3.1"
delta_sharing = "^0.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
