# Databricks notebook source
# MAGIC %sql
# MAGIC -- CREATE THE TABLES THAT ARE GOING TO BE SHARED ENABLING CHANGE DATA FEED FOR THEM
# MAGIC 
# MAGIC CREATE TABLE IF NOT EXISTS main.default.example_table (origin String, amount BIGINT) TBLPROPERTIES (delta.enableChangeDataFeed = true);

# COMMAND ----------

# MAGIC %sql
# MAGIC -- CREATE THE RECIPIENT
# MAGIC 
# MAGIC CREATE RECIPIENT IF NOT EXISTS example_recipient;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- GET THE ACTIVATION LINK FOR THE RECIPIENT (column_name: activation_link)
# MAGIC -- SHARE THE ACCESS LINK PRIVATELY AND SECURELY WITH THE RECIPIENT. AFTER THE RECIPIENT HAS RECEIVED THE LINK ON A SECURE CHANNEL, THEY NEED TO DOWNLOAD THE FILE (THAT CAN ONLY BE DOWNLAODED ONCE) AND UPLOAD IT TO WHEREVER THEY WANT TO USE DELTA SHARING
# MAGIC 
# MAGIC DESCRIBE RECIPIENT example_recipient;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- CREATE THE SHARE
# MAGIC 
# MAGIC CREATE SHARE IF NOT EXISTS example_share;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- GRANT SHARE ACCESS TO THE RECIPIENT THAT WAS CREATED EARLIER
# MAGIC 
# MAGIC GRANT SELECT ON SHARE example_share TO RECIPIENT example_recipient;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- ADD THE TABLES THAT WILL BE SHARED TO THE SHARE AND ENABLE CHANGE DATA FEED TO BE SHARED
# MAGIC 
# MAGIC ALTER SHARE example_share ADD TABLE main.default.example_table WITH CHANGE DATA FEED;
